"""
Disease-symptom probability matrix for Bayesian classifier.
P(symptom | disease) — likelihood that symptom is present given disease.
Based on veterinary literature for East African cattle diseases.
"""

DISEASES = ["lsd", "fmd", "ecf", "cbpp", "normal"]

# P(symptom=1 | disease)
SYMPTOM_LIKELIHOODS: dict[str, dict[str, float]] = {
    "lsd": {
        "skin_nodules":        0.95,
        "painless_lumps":      0.92,
        "enlarged_lymph_nodes":0.78,
        "fever":               0.72,
        "loss_of_appetite":    0.60,
        "nasal_discharge":     0.35,
        "eye_discharge":       0.40,
        "depression":          0.55,
        "swollen_lymph_nodes": 0.65,
        "mouth_blisters":      0.08,
        "tongue_sores":        0.06,
        "foot_lesions":        0.05,
        "drooling":            0.12,
        "lameness":            0.10,
        "difficulty_breathing":0.15,
        "coughing":            0.10,
        "chest_pain_signs":    0.08,
        "diarrhoea":           0.15,
        "corneal_opacity":     0.10,
        "temperature_elevated":0.72,
    },
    "fmd": {
        "mouth_blisters":      0.96,
        "tongue_sores":        0.93,
        "foot_lesions":        0.90,
        "drooling":            0.88,
        "lameness":            0.85,
        "fever":               0.78,
        "loss_of_appetite":    0.70,
        "nasal_discharge":     0.55,
        "depression":          0.60,
        "skin_nodules":        0.05,
        "painless_lumps":      0.04,
        "enlarged_lymph_nodes":0.35,
        "swollen_lymph_nodes": 0.30,
        "eye_discharge":       0.25,
        "difficulty_breathing":0.15,
        "coughing":            0.18,
        "chest_pain_signs":    0.05,
        "diarrhoea":           0.35,
        "corneal_opacity":     0.08,
        "temperature_elevated":0.78,
    },
    "ecf": {
        "fever":               0.95,
        "swollen_lymph_nodes": 0.92,
        "corneal_opacity":     0.78,
        "loss_of_appetite":    0.85,
        "depression":          0.80,
        "nasal_discharge":     0.60,
        "eye_discharge":       0.65,
        "diarrhoea":           0.55,
        "difficulty_breathing":0.50,
        "coughing":            0.45,
        "skin_nodules":        0.10,
        "painless_lumps":      0.08,
        "enlarged_lymph_nodes":0.70,
        "mouth_blisters":      0.05,
        "tongue_sores":        0.04,
        "foot_lesions":        0.03,
        "drooling":            0.15,
        "lameness":            0.35,
        "chest_pain_signs":    0.20,
        "temperature_elevated":0.92,
    },
    "cbpp": {
        "difficulty_breathing":0.95,
        "coughing":            0.92,
        "chest_pain_signs":    0.88,
        "fever":               0.82,
        "nasal_discharge":     0.75,
        "loss_of_appetite":    0.78,
        "depression":          0.72,
        "eye_discharge":       0.35,
        "diarrhoea":           0.30,
        "lameness":            0.20,
        "skin_nodules":        0.05,
        "painless_lumps":      0.04,
        "enlarged_lymph_nodes":0.45,
        "swollen_lymph_nodes": 0.50,
        "mouth_blisters":      0.05,
        "tongue_sores":        0.04,
        "foot_lesions":        0.04,
        "drooling":            0.25,
        "corneal_opacity":     0.10,
        "temperature_elevated":0.80,
    },
    "normal": {
        "fever":               0.05,
        "loss_of_appetite":    0.04,
        "skin_nodules":        0.01,
        "painless_lumps":      0.01,
        "enlarged_lymph_nodes":0.03,
        "swollen_lymph_nodes": 0.03,
        "mouth_blisters":      0.01,
        "tongue_sores":        0.01,
        "foot_lesions":        0.01,
        "drooling":            0.03,
        "lameness":            0.02,
        "nasal_discharge":     0.04,
        "eye_discharge":       0.04,
        "difficulty_breathing":0.02,
        "coughing":            0.03,
        "chest_pain_signs":    0.01,
        "diarrhoea":           0.03,
        "corneal_opacity":     0.01,
        "depression":          0.03,
        "temperature_elevated":0.05,
    },
}

# Prior probabilities — base disease rates in field conditions
DISEASE_PRIORS: dict[str, float] = {
    "lsd":    0.22,
    "fmd":    0.20,
    "ecf":    0.18,
    "cbpp":   0.15,
    "normal": 0.25,
}

DISEASE_DISPLAY: dict[str, str] = {
    "lsd":    "Lumpy Skin Disease",
    "fmd":    "Foot & Mouth Disease",
    "ecf":    "East Coast Fever",
    "cbpp":   "Contagious Bovine Pleuropneumonia",
    "normal": "No Disease Detected",
}

DISEASE_SHORT: dict[str, str] = {
    "lsd":    "LSD",
    "fmd":    "FMD",
    "ecf":    "ECF",
    "cbpp":   "CBPP",
    "normal": "Normal",
}

DISEASE_RECOMMENDATIONS: dict[str, list[str]] = {
    "lsd": [
        "Isolate the affected animal immediately from the herd",
        "Notify local animal health authority — LSD is a notifiable disease",
        "Clean and disinfect shared areas with virucidal disinfectant",
        "Contact veterinarian for confirmatory diagnosis and vaccination",
        "Monitor the rest of the herd for new skin lesions daily",
        "Control insect vectors (flies, mosquitoes) that spread LSD",
    ],
    "fmd": [
        "Restrict all herd movement immediately — do not move animals off-farm",
        "Disinfect feed, water points, equipment and footwear",
        "Notify animal health authority — FMD is a notifiable disease",
        "Provide soft feed and clean water to reduce pain from oral lesions",
        "Separate affected animals; FMD spreads very rapidly by contact",
        "Await veterinarian guidance before any treatment",
    ],
    "ecf": [
        "Contact veterinarian urgently — ECF can be fatal within 3 weeks",
        "Treat with buparvaquone (Butalex) if available and directed by vet",
        "Control ticks immediately — dip or spray with approved acaricide",
        "Isolate and shade affected animals to reduce heat stress",
        "Do not stress the animal further; avoid unnecessary handling",
        "Check and treat the whole herd for tick infestation",
    ],
    "cbpp": [
        "Isolate affected animal from herd immediately",
        "CBPP is a notifiable disease — report to local animal health authority",
        "Veterinarian may prescribe oxytetracycline or tylosin antibiotics",
        "Vaccinate healthy herd with CBPP vaccine as a preventive measure",
        "Improve ventilation in housing and avoid overcrowding",
        "Do not sell, slaughter or move animals from affected premises",
    ],
    "normal": [
        "Continue daily health observation of the animal",
        "Maintain up-to-date vaccination schedule",
        "Keep prevention, deworming and tick control records updated",
        "Ensure access to clean water and adequate nutrition",
        "Resubmit case if any new symptoms develop or condition worsens",
    ],
}
